# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Programs\Python\Network_security\sniffer\sniffer\.ui\home.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1074, 737)
        self.netcard_cb = QtWidgets.QComboBox(Form)
        self.netcard_cb.setGeometry(QtCore.QRect(100, 20, 371, 31))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        self.netcard_cb.setFont(font)
        self.netcard_cb.setStyleSheet("")
        self.netcard_cb.setObjectName("netcard_cb")
        self.listen_bt = QtWidgets.QToolButton(Form)
        self.listen_bt.setGeometry(QtCore.QRect(820, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        self.listen_bt.setFont(font)
        self.listen_bt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listen_bt.setStyleSheet("border: 2px solid rgb(85, 170, 255);\n"
"border-radius: 6px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.listen_bt.setObjectName("listen_bt")
        self.filter_line = QtWidgets.QLineEdit(Form)
        self.filter_line.setGeometry(QtCore.QRect(560, 20, 221, 31))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(11)
        self.filter_line.setFont(font)
        self.filter_line.setStyleSheet("border: 1px solid black;\n"
"border-radius: 6px;")
        self.filter_line.setObjectName("filter_line")
        self.stop_bt = QtWidgets.QToolButton(Form)
        self.stop_bt.setGeometry(QtCore.QRect(940, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        self.stop_bt.setFont(font)
        self.stop_bt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop_bt.setStyleSheet("border: 2px solid rgb(85, 170, 255);\n"
"border-radius: 6px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.stop_bt.setObjectName("stop_bt")
        self.overview_tb = QtWidgets.QTableWidget(Form)
        self.overview_tb.setGeometry(QtCore.QRect(20, 81, 1031, 271))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        self.overview_tb.setFont(font)
        self.overview_tb.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.overview_tb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overview_tb.setAutoFillBackground(False)
        self.overview_tb.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.overview_tb.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.overview_tb.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.overview_tb.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.overview_tb.setGridStyle(QtCore.Qt.SolidLine)
        self.overview_tb.setObjectName("overview_tb")
        self.overview_tb.setColumnCount(6)
        self.overview_tb.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.overview_tb.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.overview_tb.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.overview_tb.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.overview_tb.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.overview_tb.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.overview_tb.setHorizontalHeaderItem(5, item)
        self.overview_tb.horizontalHeader().setVisible(True)
        self.overview_tb.horizontalHeader().setCascadingSectionResizes(True)
        self.overview_tb.horizontalHeader().setDefaultSectionSize(125)
        self.protocol_tree = QtWidgets.QTreeWidget(Form)
        self.protocol_tree.setGeometry(QtCore.QRect(20, 380, 1031, 151))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        self.protocol_tree.setFont(font)
        self.protocol_tree.setStyleSheet("")
        self.protocol_tree.setHeaderHidden(False)
        self.protocol_tree.setColumnCount(1)
        self.protocol_tree.setObjectName("protocol_tree")
        self.code_txt = QtWidgets.QPlainTextEdit(Form)
        self.code_txt.setGeometry(QtCore.QRect(20, 560, 581, 161))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        self.code_txt.setFont(font)
        self.code_txt.setStyleSheet("")
        self.code_txt.setReadOnly(True)
        self.code_txt.setObjectName("code_txt")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 72, 31))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(480, 25, 72, 20))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 360, 91, 21))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 540, 81, 21))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 81, 21))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.statistic_txt = QtWidgets.QPlainTextEdit(Form)
        self.statistic_txt.setGeometry(QtCore.QRect(610, 560, 441, 161))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        self.statistic_txt.setFont(font)
        self.statistic_txt.setStyleSheet("")
        self.statistic_txt.setReadOnly(True)
        self.statistic_txt.setObjectName("statistic_txt")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(610, 540, 81, 21))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        width=[250, 150, 150, 100, 140, 400]
        for i in range(self.overview_tb.columnCount()):
            self.overview_tb.setColumnWidth(i, width[i])

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "WM sniffer"))
        self.listen_bt.setText(_translate("Form", "开始监听"))
        self.filter_line.setToolTip(_translate("Form", "添加捕获前过滤规则"))
        self.stop_bt.setText(_translate("Form", "停止监听"))
        item = self.overview_tb.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Time"))
        item = self.overview_tb.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Source IP"))
        item = self.overview_tb.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Target IP"))
        item = self.overview_tb.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Protocol"))
        item = self.overview_tb.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Data length"))
        item = self.overview_tb.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Information"))
        self.protocol_tree.headerItem().setText(0, _translate("Form", "Packet detail:"))
        self.label.setText(_translate("Form", "选择网卡："))
        self.label_2.setText(_translate("Form", "过滤规则："))
        self.label_3.setText(_translate("Form", "封包内容："))
        self.label_4.setText(_translate("Form", "16进制码："))
        self.label_5.setText(_translate("Form", "封包总览："))
        self.label_6.setText(_translate("Form", "统计数据："))
